movie/urls.py
from django.conf.urls import url
from . import views

app_name = 'movie'

urlpatterns = [
    # /music/
    url(r'^$',views.index,name='index'),

    #/music/712/
    url(r'^(?P<movie_id>[0-9]+)/$',views.detail,name = 'detail'),

    #/music/<movie_id>/favorite/
    url(r'^(?P<movie_id>[0-9]+)/favorite/$',views.favorite,name = 'favorite'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movie/', include('movie.urls')),
]

movie/models.py
from django.db import models

class Movie(models.Model):
    artist = models.CharField(max_length=250)#text
    movie_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    #post link to use images online
    movie_logo = models.CharField(max_length=200)

    def __str__(self): #string representation of object
        return self.movie_title + ' - ' + self.artist

class themeSong(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    file_type = models.CharField(max_length = 10)
    song_title = models.CharField(max_length = 250)
    is_favorite = models.BooleanField(default=False)


    def __str__(self):
        return self.song_title

movie/views.py
#Takes the request and sends back an HTTP response from Django HTTP

from django.http import HttpResponse
from .models import Movie, themeSong
from django.shortcuts import render, get_object_or_404
#from django.http import Http404
#from django.template import loader

# def index(request): #Connect to database and have all movie and make a link and display in http response
#     all_movies = Movie.objects.all()
#     html = ''
#     for movie in all_movies:
#         url = '/movie/' + str(movie.id) + '/'
#         html += '<a href="' + url + '">' + movie.movie_title + '</a><br>'
#     return HttpResponse(html)

def index(request):
    all_movies = Movie.objects.all()
    #template = loader.get_template('movie/index.html') #template file is referenced to index.html file

    context = {
        "all_movies":all_movies,
    }
    return render(request,'movie/index.html',context) #http response already included by render

# def detail(request, movie_id):
#     return HttpResponse("<h2>Details for Movie id: " + str(movie_id) + "</h2>")

def detail(request, movie_id):
    # try:
    #     movie = Movie.objects.get(id = movie_id)
    # except Movie.DoesNotExist:
    #     raise Http404("Movie does not exist")
    movie = get_object_or_404(Movie, pk = movie_id)
    return render(request, 'movie/detail.html', {"movie":movie})

def favorite(request, movie_id):
    movie = get_object_or_404(Movie, pk = movie_id)
    try:
        selected_song = movie.themesong_set.get(pk=request.POST['song'])
    except(KeyError, themeSong.DoesNptExist):
        return render(request, 'movie/detail.html', {'movie': movie, 'error_message': "You did not select a valid song",})
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'movie/detail.html', {"movie":movie})

movie/templates/movie/detail.html
<img src="{{movie.movie_logo}}">
<h1>{{movie.movie_title}}</h1>
<h3>{{movie.artist}}</h3>

<!--<u1>-->
    <!--{% for song in movie.themesong_set.all %}-->
    <!--<li>{{song.song_title}} - {{song.file_type}}</li>-->
    <!--{% endfor %}-->
<!--</u1>-->

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action = "{% url 'movie:favorite' movie.id %}" method = "post">
    {% csrf_token %}
    {% for song in movie.themesong_set.all %}
        <input type="radio" id="song{{forloop.counter}}" name="song" value = "{{song.id}}">
        <label for="song{{forloop.counter}}">
            {{song.song_title}}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

movie/templates/movie/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{%static 'movie/style.css' %}" />
<link rel="stylesheet" href = "maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'movie:index' %}">CAT</a>
        </div>
    </div>
</nav>

{% if all_movies %}
    <h3>Here are all my Movies</h3>
    <u1>
        {% for movie in all_movies %}
        <li><a href = "{% url 'movie:detail' movie.id%}">{{movie.movie_title}}</a></li>
        {% endfor %}
    </u1>
{% else %}}
    <h3>You don't have any movies</h3>
{% endif %}